In [5]:
import pandas as pd
student=pd.read_excel(r"C:\Users\ANSHIKA\Downloads\student_performance_dataset_34227614.xlsx")
student

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [8]:
student.sort_values(by='final_exam_score',ascending=False).head(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
381,382,Female,6.2,83.2,7.3,PhD,Yes,No,No,86.1,100.0,A
383,384,Male,6.2,90.5,6.6,High School,Yes,Yes,No,84.0,100.0,A
387,388,Male,5.0,86.9,4.9,NaN,Yes,Yes,No,100.0,100.0,A
312,313,Female,4.9,90.1,7.5,NaN,Yes,Yes,No,92.5,100.0,A
314,315,Male,2.7,88.5,7.3,Masters,Yes,Yes,No,99.3,100.0,A
315,316,Female,5.1,89.9,8.1,PhD,Yes,Yes,No,75.2,100.0,A
934,935,Female,3.6,89.4,7.0,Bachelors,Yes,No,No,95.3,100.0,A
42,43,Female,5.1,82.8,8.1,Bachelors,Yes,Yes,No,95.7,100.0,A
50,51,Male,5.9,82.5,6.6,Bachelors,Yes,Yes,No,66.5,100.0,A
948,949,Female,3.7,93.9,8.5,High School,No,No,No,93.0,100.0,A

In [13]:
student['parental_education'].unique()

<StringArray>
['Bachelors', 'High School', nan, 'Masters', 'PhD']
Length: 5, dtype: str

In [16]:
print(student.iloc[10:21][['gender','student_id','previous_grade','final_exam_score']])

    gender  student_id  previous_grade  final_exam_score
10    Male          11            73.4              68.9
11    Male          12            37.9              76.7
12    Male          13            49.0              82.6
13    Male          14            67.9              93.3
14  Female          15            71.0              73.9
15    Male          16            65.6              84.8
16  Female          17            51.0              81.5
17  Female          18            60.2              75.5
18  Female          19            74.7              89.7
19    Male          20            77.0              92.8
20  Female          21            69.8              73.5

In [20]:
student[student['gender'] == 'female'][['gender', 'previous_grade', 'final_exam_score', 'final_grade']]

Empty DataFrame
Columns: [gender, previous_grade, final_exam_score, final_grade]
Index: []

In [23]:
student1=student.copy()
student1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [24]:
student['final_exam_score'] = student['final_exam_score'].astype(float)

In [27]:
print(student['final_exam_score'].dtype)

float64

In [28]:
student = student.drop('sleep_hours', axis=1)
student

,student_id,gender,study_time_hours,attendance_percent,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,Masters,Yes,No,No,45.4,70.4,C

In [30]:
print(student.sort_values(by='final_grade', ascending=False)[['gender', 'final_exam_score', 'parental_education']])

     gender  final_exam_score parental_education
760  Female              53.2        High School
539  Female              57.3          Bachelors
715  Female              54.1        High School
364    Male              57.4          Bachelors
136    Male              59.7        High School
..      ...               ...                ...
635  Female              96.3        High School
628    Male              93.9            Masters
626    Male              96.8        High School
154    Male              95.4          Bachelors
0      Male             100.0          Bachelors

[1000 rows x 3 columns]

In [38]:

student = student.drop('part_time_job', axis=1)

print(student.iloc[:15])

KeyError: "['part_time_job'] not found in axis"

In [39]:
student['final_exam_score'] = student['final_exam_score'].astype(float)

print(student.loc[student['final_exam_score'] > 80])

     student_id  gender  study_time_hours  attendance_percent  \
0             1    Male               4.0                98.0
1             2  Female               6.3               100.0
2             3    Male               4.9                85.3
3             4    Male               2.6                77.5
5             6  Female               4.2                78.2
..          ...     ...               ...                 ...
990         991  Female               2.5                81.4
991         992  Female               5.1                71.7
993         994  Female               6.2                87.6
996         997    Male               6.7                88.4
998         999  Female               4.6                85.3

    parental_education internet_access  previous_grade  final_exam_score  \
0            Bachelors             Yes            76.9             100.0
1          High School             Yes            75.5             100.0
2            Bachelors             Yes            88.5              97.3
3                  NaN             Yes            85.1              83.8
5          High School             Yes            79.8              81.6
..                 ...             ...             ...               ...
990                NaN             Yes            81.8              81.9
991          Bachelors             Yes            51.0              80.4
993                PhD             Yes            75.4              92.7
996                NaN              No            82.2              99.5
998        High School              No            52.2              82.2

    final_grade
0             A
1             A
2             A
3             B
5             B
..          ...
990           B
991           B
993           A
996           A
998           B

[637 rows x 9 columns]

In [40]:
# Second DataFrame
school = pd.DataFrame({
    "gender": ["female", "male"],
    "Scholarship": ["Yes", "No"]
})

# Merge the DataFrames
merged = pd.merge(student, school, on="gender")

print(merged)

Empty DataFrame
Columns: [student_id, gender, study_time_hours, attendance_percent, parental_education, internet_access, previous_grade, final_exam_score, final_grade, Scholarship]
Index: []